version: "3"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA="Y"
            - SA_PASSWORD=wq5p5*YQ#N
    redis:
       image: redis
       ports:
        - "6379:6379"